## Исключительные ситуации

Исключительная ситуация - ошибка, возникающая в процессе работы программы.\
В языке уже имеются описанные исключительные ситуации, но также, имеется вохможность разрабатывать свои собственные.

### 1. Обработка исключительных ситуаций
Блок кода, в котором предпологается возникновение каких-либо ошибок, необходимо поместить внутрь оператора <code>try...catch</code>.
```c++
try
{
    инструкции_приводящие_к_ошибке    
}
catch (тип_исключения переменная)
{
    обработка_исключения
}
[catch(тип_исключения_2 переменная)
{
    ...
}]
```

Если в тип исключения передать <code>...</code>, это позволит обработать любое исключение <code>catch(...)</code>.

### 2. Генерация собственного исключения
Для генерации исключения используется оператор <code>throw</code>.
```c++
throw значение_исключения;
```
В блоке <code>catch</code> можно получить значение исключения.

### 3. Класс <code>exception</code>
Базовый класс для всех исключений. Описан в заголовочном файле <code>exception</code>.

#### Создание производного класса исключений
На основе класса <code>exception</code> можно создавать собственные типы исключений.
```c++
class example_exception: std::exception
{
public:
    example_exception(const std::string& message): message{message}{}
    const char* what() const noexcept override
    {
        return message.c_str();
    }
private:
    std::string message;
}

// Генерация исключения
throw example_exception("Сообщение");
```

### 4. Список классов исключений
> <code>runtime_error</code> базовый тип исключений, возникающих во время выполнения программы.
> - <code>range_error</code> возникает, когда результат превосходит допустимый диапазон.
> - <code>overflow_error</code> возникает, если полученный результат превышает допустимый диапазон.
> - <code>underflow_error</code> возникает, если полученный в вычислениях результат имеет недопустимое отрицательное значение.

> <code>logic_error</code> возникает при наличии логических ошибок к коде программы.
> - <code>domain_error</code> возникает, если для некоторого значения, передаваемого в функцию, не определен результат.
> - <code>invalid_argument</code> возникает при передаче в функцию некорректного аргумента.
> - <code>length_error</code> которое возникает при попытке создать объект большего размера, чем допустим для данного типа.
> - <code>out_of_range</code> возникает при попытке доступа к элементам вне допустимого диапазона.
